version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: tabprojekt
      POSTGRES_USER: tabprojekt
      POSTGRES_DB: tabprojekt
    ports:
      - 6543:5432
  
  backend:
    image: nixen/yggdrasil:latest
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tabprojekt
      - SPRING_DATASOURCE_USERNAME=tabprojekt
      - SPRING_DATASOURCE_PASSWORD=tabprojekt
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    depends_on:
      - db
