version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: tabprojekt
      POSTGRES_USER: tabprojekt
      POSTGRES_DB: tabprojekt
    ports:
      - 5432:5432