on:
  push:
    branches:
      - main
      - development
      - devops

jobs:
  hack:
    runs-on: ubuntu-latest
    outputs:
      environment_name: ${{ steps.get_environment.outputs.environment_name }}
    steps:
      - id: get_environment
        run: echo "::set-output name=environment-name::$(echo ${GITHUB_REF#refs/heads/})"
  build:
    needs: [hack]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.hack.output.environment_name }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: cd server && make build
      - name: Copy artifact to main directory
        run: cd server && mkdir artifacts && cp target/*.jar artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Backend JAR file
          path: server/artifacts/*.jar
      - name: Make docker image
        run: cd server && docker login -u nixen -p "${TOKEN}" && TAG_NAME="${TAG-NAME}" make build-docker && TAG_NAME="${TAG-NAME}" make publish-docker
        env:
          TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          TAG-NAME: ${{ secrets.TAG_NAME }}